# This file is meant to serve as a template for other configuration files and also defines the default values for
# configuration for the PlayBook service. See (https://github.com/lorenwest/node-config/wiki/Configuration-Files) for
# more details on how the Node.js 'config' library works with these files.

# Default database configuration
database:
    host: localhost
    port: 27017
    name: gaptasks

# Default server configurations
server:
    host: localhost
    port: 8585

# Default security configurations. These are mainly used to assist with creation/verification of JSON Web Tokens
# to authenticate requests
security:
    hashAlgo: sha256
    jwt:
        audience: gaptasks.com/api
        issuer: gaptasks.com
        secretKey: /etc/secrets/private.key

chatkit:
    instanceLocator: "v1:us1:4eb3c1bc-724a-48f8-9d96-8a5f58b9da94"
    key: "33486da8-cecd-494a-8b0a-65f966705fc8:9wiZSYbOoybMwNw66ufbcRzUk1dFqMbQWtDI4qp3P/k="

